#!/bin/zsh
FASTLY_PATH='static/file3.html?showkeys=1'
#curl -Lvvs 'https://$FASTLY_HOST/$FASTLY_PATH
echo
echo "curl -Is 'https://$FASTLY_HOST/$FASTLY_PATH'"
echo 
curl -Is "https://$FASTLY_HOST/$FASTLY_PATH"
